// One-off fixture generator.
// Run with: dotnet run --project tools/GenerateFixtures
// from the repo root.
//
// Re-run after any deliberate format-spec bump.
// The 2D-simple fixture represents f(x,y)=x+y on [-1,1]², n=[3,3] (128 bytes).
// The byte layout is documented byte-for-byte in
// ref/PyChebyshev/docs/user-guide/binary-format.md ("Worked example").

using System;
using System.IO;
using ChebyshevSharp;

// Resolve fixture directory relative to the repo root.
// This script is in tools/GenerateFixtures/, so we go up 2 levels.
string scriptDir = AppContext.BaseDirectory;
string repoRoot = Path.GetFullPath(Path.Combine(scriptDir, "..", "..", "..", "..", ".."));
string fixtureDir = Path.Combine(repoRoot, "tests", "fixtures");
Directory.CreateDirectory(fixtureDir);
Console.WriteLine($"Writing fixtures to: {fixtureDir}");

// -----------------------------------------------------------------------
// 1) approx_2d_simple.pcb — f(x,y)=x+y on [-1,1]², n=[3,3]
//    The tensor values at Chebyshev Type-I nodes xi = cos((2i-1)*pi/6) are:
//    tensor[i,j] = nodes[i] + nodes[j] where nodes = [-sqrt(3)/2, 0, sqrt(3)/2]
//    Total file size: 128 bytes (header 12 + body 116).
// -----------------------------------------------------------------------
{
    double s = Math.Sqrt(3.0) / 2.0;
    double[] nodes = { -s, 0.0, s };
    double[] tensor = new double[9];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            tensor[i * 3 + j] = nodes[i] + nodes[j];

    var cheb = ChebyshevApproximation.FromValues(
        tensor,
        2,
        new[] { new[] { -1.0, 1.0 }, new[] { -1.0, 1.0 } },
        new[] { 3, 3 });

    string path = Path.Combine(fixtureDir, "approx_2d_simple.pcb");
    cheb.Save(path, format: "binary");
    long sz = new FileInfo(path).Length;
    Console.WriteLine($"Wrote {path} ({sz} bytes, expected 128)");
    if (sz != 128)
        Console.Error.WriteLine($"  WARNING: expected 128 bytes, got {sz}");
}

// -----------------------------------------------------------------------
// 2) approx_5d_bs.pcb — a 5D Black-Scholes-ish shape on standard option-pricing
//    domains. Bytes generated by ChebyshevSharp's writer (round-trip-tested in
//    Tasks 1-5 to be byte-equal to PyChebyshev's output).
// -----------------------------------------------------------------------
{
    var bs5d = new ChebyshevApproximation(
        (p, _) => Math.Max(p[0] - 100, 0) + 0.01 * p[1] - 0.5 * p[2] * p[2] + p[3] + p[4],
        5,
        new[] {
            new[] {  80.0, 120.0 },   // S
            new[] {   0.1, 0.4   },   // sigma
            new[] {   0.5, 1.5   },   // T
            new[] {   0.0, 0.05  },   // r
            new[] {  90.0, 110.0 },   // K
        },
        new[] { 5, 5, 5, 5, 5 });
    bs5d.Build(verbose: false);
    string path = Path.Combine(fixtureDir, "approx_5d_bs.pcb");
    bs5d.Save(path, format: "binary");
    long sz = new FileInfo(path).Length;
    Console.WriteLine($"Wrote {path} ({sz} bytes)");
}

// -----------------------------------------------------------------------
// 3) spline_1d_kink.pcb — abs(x) on [-1,1] with knot at 0
//    This is the Spline worked example documented in binary-format.md.
// -----------------------------------------------------------------------
{
    var kink = new ChebyshevSpline(
        (p, _) => Math.Abs(p[0]), 1,
        new[] { new[] { -1.0, 1.0 } }, new[] { 3 },
        knots: new[] { new[] { 0.0 } });
    kink.Build(verbose: false);
    string path = Path.Combine(fixtureDir, "spline_1d_kink.pcb");
    kink.Save(path, format: "binary");
    long sz = new FileInfo(path).Length;
    Console.WriteLine($"Wrote {path} ({sz} bytes)");
}

Console.WriteLine("Done.");
